### ISSUE TITLE
Support encrypted values

### ISSUE THREAD

**Issue by andrepiske** [andrepiske/comff#1]
Allow certain values to be encrypted.

If using [rbnacl](https://github.com/RubyCrypto/rbnacl), make sure that using C extensions isn't a requirement for using comff. Maybe just using OpenSSL is enough and it's bundled with Ruby already.

An idea on how encrypted values could look like:
```yaml
foo: not-encrypted-value
bar:
  qux:
    - format: encrypted
      value: !binary |
        c29tZSBhY3R1YWwgZW5jcnlwdGVkIHZhbHVl
```

The `!binary` notation is standard yaml:
```ruby
YAML.safe_load( ... the string above ... ) == {"foo"=>"not-encrypted-value", "bar"=>{"qux"=>[{"format"=>"encrypted", "value"=>"some actual encrypted value"}]}}
```

The questions, however, is how encrypted values would be passed when using environment variables.
